-- Fixed seed data for Jovie MVP
-- Matches the schema from 00000000000000_baseline.sql

-- App users - matches the baseline schema app_users
INSERT INTO app_users (id, email) VALUES 
  ('seed_user_1', 'artist1@example.com'),
  ('seed_user_2', 'artist2@example.com'),
  ('seed_user_3', 'artist3@example.com'),
  ('seed_user_4', 'podcaster1@example.com'),
  ('seed_user_5', 'influencer1@example.com'),
  ('seed_user_6', 'tim@example.com'),
  ('seed_user_7', 'taylorswift@example.com'),
  ('seed_user_8', 'oliviarodrigo@example.com'),
  ('seed_user_9', 'sza@example.com'),
  ('seed_user_10', 'theweeknd@example.com'),
  ('seed_user_11', 'badbunny@example.com'),
  ('seed_user_12', 'karolg@example.com'),
  ('seed_user_13', 'newjeans@example.com'),
  ('seed_user_14', 'maneskin@example.com'),
  ('seed_user_15', 'pinkpantheress@example.com'),
  ('seed_user_16', 'lukecombs@example.com')
ON CONFLICT (id) DO NOTHING;

-- Creator profiles - only using columns that exist in baseline schema
INSERT INTO creator_profiles (
  user_id, 
  creator_type, 
  username, 
  display_name, 
  bio, 
  avatar_url, 
  spotify_url, 
  apple_music_url, 
  youtube_url, 
  spotify_id, 
  is_public, 
  is_verified,
  theme,
  settings
) VALUES
  (
    'seed_user_1', 
    'artist', 
    'musicmaker', 
    'Music Maker', 
    'I create electronic music and love to collaborate. Known for ambient soundscapes and deep house tracks that take you on a journey.', 
    '/images/avatars/music-maker.jpg',
    'https://open.spotify.com/artist/example123',
    'https://music.apple.com/us/artist/music-maker/example123',
    'https://youtube.com/@musicmaker',
    'example123spotify',
    true,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_2', 
    'artist', 
    'privateartist', 
    'Private Artist', 
    'This is a private profile for testing RLS. Only authenticated users should see this.', 
    null,
    null,
    null,
    null,
    null,
    false,
    false,
    null,
    '{"hide_branding": true}'
  ),
  (
    'seed_user_3', 
    'artist', 
    'popstar', 
    'Pop Star', 
    'Chart-topping hits and energetic performances! Latest single "Dreams Come True" out now on all platforms.', 
    '/images/avatars/pop-star.jpg',
    'https://open.spotify.com/artist/popstar456',
    'https://music.apple.com/us/artist/pop-star/456789',
    'https://youtube.com/@popstarofficial',
    'popstar456',
    true,
    true,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_4', 
    'podcaster', 
    'techtalks', 
    'Tech Talks Podcast', 
    'Weekly deep dives into the latest technology trends, startup stories, and interviews with industry leaders.', 
    '/images/avatars/tech-talks.jpg',
    null,
    null,
    'https://youtube.com/@techtalks',
    null,
    true,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_5', 
    'influencer', 
    'lifestyleguru', 
    'Lifestyle Guru', 
    'Sharing inspiration for mindful living, wellness tips, and sustainable fashion choices. Join my journey to better living!', 
    '/images/avatars/lifestyle-guru.jpg',
    null,
    null,
    'https://youtube.com/@lifestyleguru',
    null,
    true,
    true,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_6', 
    'artist', 
    'tim', 
    'Tim White', 
    'Independent artist exploring electronic and ambient sounds. Latest release: "Never Say A Word" (2024).', 
    'https://i.scdn.co/image/ab6761610000e5ebbab7ca6e76db7da72b58aa5c',
    null,
    null,
    null,
    null,
    true,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_7', 
    'artist', 
    'taylorswift', 
    'Taylor Swift', 
    'Singer-songwriter with multiple Grammy Awards. Known for storytelling through music across country, pop, and folk genres.', 
    'https://i.scdn.co/image/ab6761610000e5eb859e4fdcae060b15797769b3',
    'https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02',
    'https://music.apple.com/us/artist/taylor-swift/159260351',
    'https://youtube.com/@TaylorSwift',
    '06HL4z0CvFAxyc27GXpf02',
    true,
    true,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_8', 
    'artist', 
    'oliviarodrigo', 
    'Olivia Rodrigo', 
    'Singer-songwriter and actress. Grammy winner known for "drivers license" and albums "SOUR" and "GUTS".', 
    'https://i.scdn.co/image/ab6761610000e5ebe03a98785f3658f0b6461ec4',
    'https://open.spotify.com/artist/1McMsnEElThX1knmY9oliG',
    'https://music.apple.com/us/artist/olivia-rodrigo/1440623969',
    'https://youtube.com/@OliviaRodrigo',
    '1McMsnEElThX1knmY9oliG',
    true,
    true,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_9', 
    'artist', 
    'sza', 
    'SZA', 
    'R&B singer-songwriter known for introspective lyrics and smooth vocals. Grammy-nominated artist with albums "Ctrl" and "SOS".', 
    'https://i.scdn.co/image/ab6761610000e5eb0895066d172e1f51f520bc65',
    'https://open.spotify.com/artist/7tYKF4w9nC0nq9CsPZTHyP',
    'https://music.apple.com/us/artist/sza/1050239550',
    'https://youtube.com/@sza',
    '7tYKF4w9nC0nq9CsPZTHyP',
    true,
    true,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_10', 
    'artist', 
    'theweeknd', 
    'The Weeknd', 
    'Multi-platinum recording artist known for hits like "Blinding Lights" and "Can''t Feel My Face". Three-time Grammy winner.', 
    'https://i.scdn.co/image/ab6761610000e5eb214f3cf1cbe7139c1e26ffbb',
    'https://open.spotify.com/artist/1Xyo4u8uXC1ZmMpatF05PJ',
    'https://music.apple.com/us/artist/the-weeknd/479756766',
    'https://youtube.com/@theweeknd',
    '1Xyo4u8uXC1ZmMpatF05PJ',
    true,
    true,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_11', 
    'artist', 
    'badbunny', 
    'Bad Bunny', 
    'Puerto Rican reggaeton and Latin trap artist. Global superstar known for "Un Verano Sin Ti" and collaborations worldwide.', 
    'https://i.scdn.co/image/ab6761610000e5eb4c1d23de5dd3c7ed3e10b7e1',
    'https://open.spotify.com/artist/4q3ewBCX7sLwd24euuV69X',
    'https://music.apple.com/us/artist/bad-bunny/1126808565',
    'https://youtube.com/@badbunnypr',
    '4q3ewBCX7sLwd24euuV69X',
    true,
    true,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_12', 
    'artist', 
    'karolg', 
    'KAROL G', 
    'Colombian reggaeton artist and Latin Grammy winner. Known for empowering anthems and hits like "Tusa" and "Provenza".', 
    'https://i.scdn.co/image/ab6761610000e5ebec0a39e27f8a8b96e7d3d9d5',
    'https://open.spotify.com/artist/790FomKkXshlbRYZFtlgla',
    'https://music.apple.com/us/artist/karol-g/1133792108',
    'https://youtube.com/@KarolG',
    '790FomKkXshlbRYZFtlgla',
    true,
    true,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_13', 
    'artist', 
    'newjeans', 
    'NewJeans', 
    'K-pop girl group known for their Y2K-inspired sound and visuals. Members: Minji, Hanni, Danielle, Haerin, and Hyein.', 
    'https://i.scdn.co/image/ab6761610000e5ebdbc0ffede80a6a0eebdb6b3d',
    'https://open.spotify.com/artist/6HvZYsbFfjnjFrWF950C9d',
    'https://music.apple.com/us/artist/newjeans/1640048757',
    'https://youtube.com/@NewJeans_official',
    '6HvZYsbFfjnjFrWF950C9d',
    true,
    true,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_14', 
    'artist', 
    'maneskin', 
    'Måneskin', 
    'Italian rock band that won Eurovision 2021. Known for their energetic performances and hits like "Beggin''" and "I Wanna Be Your Slave".', 
    'https://i.scdn.co/image/ab6761610000e5eb6ebc5eb9e76da4b30e7e6e8b',
    'https://open.spotify.com/artist/3qM84nBOXUEQ2vnTfUTTFC',
    'https://music.apple.com/us/artist/måneskin/1251886477',
    'https://youtube.com/@ManeskinOfficial',
    '3qM84nBOXUEQ2vnTfUTTFC',
    true,
    true,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_15', 
    'artist', 
    'pinkpantheress', 
    'PinkPantheress', 
    'British singer-songwriter blending Y2K nostalgia with modern production. Known for viral hits and dreamy, nostalgic soundscapes.', 
    'https://i.scdn.co/image/ab6761610000e5ebb71c0986c96e3f4eca3f16e4',
    'https://open.spotify.com/artist/9nqJZe8XLi6mHyQhEWCRH0',
    'https://music.apple.com/us/artist/pinkpantheress/1560624444',
    'https://youtube.com/@PinkPantheress',
    '9nqJZe8XLi6mHyQhEWCRH0',
    true,
    true,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_16', 
    'artist', 
    'lukecombs', 
    'Luke Combs', 
    'Country music superstar with multiple #1 hits. Known for authentic songwriting and powerful vocals in songs like "Hurricane" and "Beautiful Crazy".', 
    'https://i.scdn.co/image/ab6761610000e5eb42d71b5a7a9c96ddb4b8e3d7',
    'https://open.spotify.com/artist/718COspgdWOnwOFpJHRZHS',
    'https://music.apple.com/us/artist/luke-combs/549799352',
    'https://youtube.com/@LukeCombs',
    '718COspgdWOnwOFpJHRZHS',
    true,
    true,
    null,
    '{"hide_branding": false}'
  )
ON CONFLICT (username) DO NOTHING;