-- Enhanced seed data for new Clerk-Supabase integration schema
-- This file contains comprehensive seed data for testing all features

-- Additional seed data beyond what's in the baseline migration
-- The baseline migration already includes basic test users and profiles

-- Add more diverse and complete test profiles for development
INSERT INTO app_users (id, email) VALUES 
  ('seed_user_1', 'artist1@example.com'),
  ('seed_user_2', 'artist2@example.com'),
  ('seed_user_3', 'artist3@example.com'),
  ('seed_user_4', 'podcaster1@example.com'),
  ('seed_user_5', 'influencer1@example.com'),
  ('seed_user_6', 'tim@example.com'),
  ('seed_user_7', 'taylorswift@example.com'),
  ('seed_user_8', 'oliviarodrigo@example.com'),
  ('seed_user_9', 'sza@example.com'),
  ('seed_user_10', 'theweeknd@example.com'),
  ('seed_user_11', 'badbunny@example.com'),
  ('seed_user_12', 'karolg@example.com'),
  ('seed_user_13', 'newjeans@example.com'),
  ('seed_user_14', 'maneskin@example.com'),
  ('seed_user_15', 'pinkpantheress@example.com'),
  ('seed_user_16', 'lukecombs@example.com')
ON CONFLICT (id) DO NOTHING;

-- Create comprehensive profiles with all fields populated
INSERT INTO creator_profiles (
  user_id, 
  creator_type, 
  username, 
  display_name, 
  bio, 
  avatar_url, 
  spotify_url, 
  apple_music_url, 
  youtube_url, 
  spotify_id, 
  is_public, 
  is_verified,
  is_featured,
  marketing_opt_out,
  theme,
  settings
) VALUES
  (
    'seed_user_1', 
    'artist', 
    'musicmaker', 
    'Music Maker', 
    'I create electronic music and love to collaborate. Known for ambient soundscapes and deep house tracks that take you on a journey.', 
    '/images/avatars/music-maker.jpg',
    'https://open.spotify.com/artist/example123',
    'https://music.apple.com/us/artist/music-maker/example123',
    'https://youtube.com/@musicmaker',
    'example123spotify',
    true,
    false,
    true,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_2', 
    'artist', 
    'privateartist', 
    'Private Artist', 
    'This is a private profile for testing RLS. Only authenticated users should see this.', 
    null,
    null,
    null,
    null,
    null,
    false,
    false,
    false,
    false,
    null,
    '{"hide_branding": true}'
  ),
  (
    'seed_user_3', 
    'artist', 
    'popstar', 
    'Pop Star', 
    'Chart-topping hits and energetic performances! 🎤✨ Latest single "Dreams Come True" out now on all platforms.', 
    '/images/avatars/pop-star.jpg',
    'https://open.spotify.com/artist/popstar456',
    'https://music.apple.com/us/artist/pop-star/456789',
    'https://youtube.com/@popstarofficial',
    'popstar456',
    true,
    true,
    true,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_4', 
    'podcaster', 
    'techtalks', 
    'Tech Talks Podcast', 
    'Weekly deep dives into the latest technology trends, startup stories, and interviews with industry leaders.', 
    '/images/avatars/tech-talks.jpg',
    null,
    null,
    'https://youtube.com/@techtalks',
    null,
    true,
    false,
    false,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_5', 
    'influencer', 
    'lifestyleguru', 
    'Lifestyle Guru', 
    'Sharing daily inspiration, wellness tips, and authentic life moments. Join my journey to mindful living! 🌱', 
    null,
    null,
    null,
    'https://youtube.com/@lifestyleguru',
    null,
    true,
    false,
    false,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_6', 
    'artist', 
    'tim', 
    'Tim White', 
    null, 
    'https://i.scdn.co/image/ab6761610000e5eb7f33b92be7bfa3a7edccf9f6', 
    'https://open.spotify.com/artist/4Uwpa6zW3zzCSQvooQNksm', 
    'https://music.apple.com/us/artist/tim-white/1153130306',
    'https://www.youtube.com/@TimWhiteMusic',
    '4Uwpa6zW3zzCSQvooQNksm', 
    true, 
    true, 
    true,
    false,
    null, 
    '{"hide_branding": false}'
  ),
  (
    'seed_user_7',
    'artist',
    'taylorswift',
    'Taylor Swift',
    null,
    'https://i.scdn.co/image/ab6761610000e5eb8a5b8f6b893881c7b6d2b7b4',
    'https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02',
    'https://music.apple.com/us/artist/taylor-swift/159260351',
    'https://www.youtube.com/@TaylorSwift',
    '06HL4z0CvFAxyc27GXpf02',
    true,
    true,
    true,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_8',
    'artist',
    'oliviarodrigo',
    'Olivia Rodrigo',
    null,
    'https://i.scdn.co/image/ab6761610000e5eb4a3f7cfa0b1e2e0f9a6c1d3a',
    'https://open.spotify.com/artist/1McMsnEElThX1knmY4oliG',
    'https://music.apple.com/us/artist/olivia-rodrigo/979458609',
    'https://www.youtube.com/@OliviaRodrigo',
    '1McMsnEElThX1knmY4oliG',
    true,
    true,
    true,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_9',
    'artist',
    'sza',
    'SZA',
    null,
    'https://i.scdn.co/image/ab6761610000e5eb1b8b5e6b8e1c1b6c1d3a2d6a',
    'https://open.spotify.com/artist/7tYKF4w9nC0nq9CsPZTHyP',
    'https://music.apple.com/us/artist/sza/6058036',
    'https://www.youtube.com/@szavevo',
    '7tYKF4w9nC0nq9CsPZTHyP',
    true,
    true,
    true,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_10',
    'artist',
    'theweeknd',
    'The Weeknd',
    null,
    'https://i.scdn.co/image/ab6761610000e5eb02eac6f7dfb1c6e3c2a2b6b7',
    'https://open.spotify.com/artist/1Xyo4u8uXC1ZmMpatF05PJ',
    'https://music.apple.com/us/artist/the-weeknd/479756766',
    'https://www.youtube.com/@TheWeeknd',
    '1Xyo4u8uXC1ZmMpatF05PJ',
    true,
    true,
    true,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_11',
    'artist',
    'badbunny',
    'Bad Bunny',
    null,
    'https://i.scdn.co/image/ab6761610000e5ebce20f65e6b7b7c2b8e1c6a7a',
    'https://open.spotify.com/artist/4q3ewBCX7sLwd24euuV69X',
    'https://music.apple.com/us/artist/bad-bunny/1126808565',
    'https://www.youtube.com/@badbunnypr',
    '4q3ewBCX7sLwd24euuV69X',
    true,
    true,
    true,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_12',
    'artist',
    'karolg',
    'KAROL G',
    null,
    'https://i.scdn.co/image/ab6761610000e5eb7c0e6b6a7d2b8b6e1c2d8e7a',
    'https://open.spotify.com/artist/790FomKkXshlbRYZFtlgla',
    'https://music.apple.com/us/artist/karol-g/1178330690',
    'https://www.youtube.com/@KarolG',
    '790FomKkXshlbRYZFtlgla',
    true,
    true,
    true,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_13',
    'artist',
    'newjeans',
    'NewJeans',
    null,
    'https://i.scdn.co/image/ab6761610000e5ebc2c6d6b6e7e7b2b8a1c7d2d8',
    'https://open.spotify.com/artist/6HvZYsbFfjnjFrWF950C9d',
    'https://music.apple.com/us/artist/newjeans/1633416360',
    'https://www.youtube.com/@NewJeans_official',
    '6HvZYsbFfjnjFrWF950C9d',
    true,
    true,
    true,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_14',
    'artist',
    'maneskin',
    'Måneskin',
    null,
    'https://i.scdn.co/image/ab6761610000e5eb7d2b8e7a2d6c1b6e8a6c7d2a',
    'https://open.spotify.com/artist/3MZsBdqDrRTJihTHQrO6Dq',
    'https://music.apple.com/us/artist/m%C3%A5neskin/1185737265',
    'https://www.youtube.com/@ManeskinOfficial',
    '3MZsBdqDrRTJihTHQrO6Dq',
    true,
    true,
    true,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_15',
    'artist',
    'pinkpantheress',
    'PinkPantheress',
    null,
    'https://i.scdn.co/image/ab6761610000e5ebd6a1c7d2e7b8c2b8e1d2b7a7',
    'https://open.spotify.com/artist/78rUTD7y6Cy67W1RVzYs7t',
    'https://music.apple.com/us/artist/pinkpantheress/1569878847',
    'https://www.youtube.com/@pinkpantheress',
    '78rUTD7y6Cy67W1RVzYs7t',
    true,
    true,
    true,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    'seed_user_16',
    'artist',
    'lukecombs',
    'Luke Combs',
    null,
    'https://i.scdn.co/image/ab6761610000e5ebd2b7b8e1c6a7d2b8c7e8a1c6',
    'https://open.spotify.com/artist/718COspgdWOnwOFpJHRZHS',
    'https://music.apple.com/us/artist/luke-combs/1088828794',
    'https://www.youtube.com/@LukeCombs',
    '718COspgdWOnwOFpJHRZHS',
    true,
    true,
    true,
    false,
    null,
    '{"hide_branding": false}'
  )
ON CONFLICT (username) DO NOTHING;

-- Add some unclaimed profiles that can be claimed later
-- These profiles exist without a user_id and can be claimed by future users
INSERT INTO creator_profiles (
  user_id,
  creator_type, 
  username, 
  display_name, 
  bio, 
  avatar_url, 
  spotify_url, 
  apple_music_url, 
  youtube_url, 
  spotify_id, 
  is_public, 
  is_verified,
  is_featured,
  marketing_opt_out,
  is_claimed,
  theme,
  settings
) VALUES
  (
    NULL, -- No user_id - this is unclaimed
    'artist',
    'beyonce',
    'Beyoncé',
    'Global superstar, cultural icon, and Queen B. Grammy Award-winning artist with legendary performances and timeless music.',
    'https://i.scdn.co/image/ab6761610000e5eb12d5ab979779aa280d5de252',
    'https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m',
    'https://music.apple.com/us/artist/beyonc%C3%A9/1419227',
    'https://www.youtube.com/@beyonce',
    '6vWDO969PvNqNYHIOW5v0m',
    true,
    true,
    true,
    false,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    NULL,
    'artist',
    'dualipa',
    'Dua Lipa',
    'British pop sensation with chart-topping hits. Known for dance-pop anthems and powerful vocals.',
    'https://i.scdn.co/image/ab6761610000e5eb6a48a236064d4e47966fdc4f',
    'https://open.spotify.com/artist/6M2wZ9GZgrQXHCFfjv46we',
    'https://music.apple.com/us/artist/dua-lipa/1065681363',
    'https://www.youtube.com/@DuaLipa',
    '6M2wZ9GZgrQXHCFfjv46we',
    true,
    true,
    true,
    false,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    NULL,
    'artist',
    'arianagrande',
    'Ariana Grande',
    'Pop icon with incredible vocal range. Multiple Grammy winner and chart-topping artist.',
    'https://i.scdn.co/image/ab6761610000e5ebcdce7620dc940db079bf4952',
    'https://open.spotify.com/artist/66CXWjxzNUsdJxJ2JdwvnR',
    'https://music.apple.com/us/artist/ariana-grande/12131546',
    'https://www.youtube.com/@arianagrande',
    '66CXWjxzNUsdJxJ2JdwvnR',
    true,
    true,
    true,
    false,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    NULL,
    'artist',
    'edsheeran',
    'Ed Sheeran',
    'British singer-songwriter with global hits. Master of acoustic pop and heartfelt lyrics.',
    'https://i.scdn.co/image/ab6761610000e5eb12a2ef08d00dd7451a6dbed6',
    'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V',
    'https://music.apple.com/us/artist/ed-sheeran/183313439',
    'https://www.youtube.com/@EdSheeran',
    '6eUKZXaKkcviH0Ku9w2n3V',
    true,
    true,
    true,
    false,
    false,
    null,
    '{"hide_branding": false}'
  ),
  (
    NULL,
    'artist',
    'billieeilish',
    'Billie Eilish',
    'Genre-defying artist with haunting vocals and unique style. Multiple Grammy winner and Gen Z icon.',
    'https://i.scdn.co/image/ab6761610000e5eb50defaf9fc059a1efc541f4c',
    'https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd8DAH',
    'https://music.apple.com/us/artist/billie-eilish/1065981054',
    'https://www.youtube.com/@billieeilish',
    '6qqNVTkY8uBg9cP3Jd8DAH',
    true,
    true,
    true,
    false,
    false,
    null,
    '{"hide_branding": false}'
  )
ON CONFLICT (username) DO NOTHING;
