-- Enhanced Creator Profiles Seed Data
-- Full profiles with comprehensive bio and social links for demo artists

-- First, ensure we have app_users for each artist (simulating real user accounts)
INSERT INTO app_users (id, email) VALUES
  ('user_ladygaga', 'ladygaga@example.com'),
  ('user_davidguetta', 'davidguetta@example.com'),
  ('user_billieeilish', 'billieeilish@example.com'),
  ('user_marshmello', 'marshmello@example.com'),
  ('user_rihanna', 'rihanna@example.com'),
  ('user_calvinharris', 'calvinharris@example.com'),
  ('user_sabrinacarpenter', 'sabrinacarpenter@example.com'),
  ('user_thechainsmokers', 'thechainsmokers@example.com'),
  ('user_dualipa', 'dualipa@example.com'),
  ('user_31WSX2aM04NNT8bFAQppljnGuGN', 't@timwhite.co')
ON CONFLICT (id) DO NOTHING;

-- Insert enhanced creator profiles with full bio and social information
INSERT INTO creator_profiles (
  user_id, 
  creator_type, 
  username, 
  display_name, 
  bio, 
  avatar_url,
  spotify_url,
  apple_music_url,
  youtube_url,
  spotify_id,
  is_public,
  is_verified,
  settings
) VALUES
  (
    'user_ladygaga',
    'artist',
    'ladygaga',
    'Lady Gaga',
    'Grammy and Oscar-winning artist, actress, and activist. Known for hits like "Bad Romance," "Poker Face," and "Shallow." Born This Way Foundation founder.',
    'https://i.scdn.co/image/ab6761610000e5ebc36dd9eb55fb0db4911f25dd',
    'https://open.spotify.com/artist/1HY2Jd0NmPuamShAr6KMms',
    'https://music.apple.com/us/artist/lady-gaga/277293880',
    'https://youtube.com/@ladygaga',
    '1HY2Jd0NmPuamShAr6KMms',
    true,
    true,
    '{"hide_branding": false}'::jsonb
  ),
  (
    'user_davidguetta',
    'artist',
    'davidguetta',
    'David Guetta',
    'French DJ, record producer, and songwriter. Pioneer of electronic dance music with over 50 million records sold worldwide. Grammy Award winner.',
    'https://i.scdn.co/image/ab6761610000e5eb150e1b9e6ae26e8d7b3fb5a2',
    'https://open.spotify.com/artist/1Cs0zKBU1kc0i8ypK3B9ai',
    'https://music.apple.com/us/artist/david-guetta/5468295',
    'https://youtube.com/@davidguetta',
    '1Cs0zKBU1kc0i8ypK3B9ai',
    true,
    true,
    '{"hide_branding": false}'::jsonb
  ),
  (
    'user_billieeilish',
    'artist',
    'billieeilish',
    'Billie Eilish',
    'Grammy-winning singer-songwriter known for her unique style and introspective lyrics. Album "When We All Fall Asleep, Where Do We Go?" changed pop music.',
    'https://i.scdn.co/image/ab6761610000e5eb7aa2e8b4b7b87781b1c4dc52',
    'https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH',
    'https://music.apple.com/us/artist/billie-eilish/1065981054',
    'https://youtube.com/@billieeilish',
    '6qqNVTkY8uBg9cP3Jd7DAH',
    true,
    true,
    '{"hide_branding": false}'::jsonb
  ),
  (
    'user_marshmello',
    'artist',
    'marshmello',
    'Marshmello',
    'Electronic music producer and DJ known for progressive house and future bass. Collaborations with Bastille, Khalid, and Selena Gomez. Always masked performer.',
    'https://i.scdn.co/image/ab6761610000e5eba85b8b1a09c9bf5b5e0dad0e',
    'https://open.spotify.com/artist/64KEffDW9EtZ1y2vBYgq8T',
    'https://music.apple.com/us/artist/marshmello/1115976606',
    'https://youtube.com/@marshmello',
    '64KEffDW9EtZ1y2vBYgq8T',
    true,
    true,
    '{"hide_branding": false}'::jsonb
  ),
  (
    'user_rihanna',
    'artist',
    'rihanna',
    'Rihanna',
    'Barbadian singer, actress, and businesswoman. One of the best-selling music artists with over 250 million records sold. Fenty Beauty and Savage X Fenty founder.',
    'https://i.scdn.co/image/ab6761610000e5eb99e4fca7c0b7cb166d915789',
    'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H',
    'https://music.apple.com/us/artist/rihanna/52486395',
    'https://youtube.com/@rihanna',
    '5pKCCKE2ajJHZ9KAiaK11H',
    true,
    true,
    '{"hide_branding": false}'::jsonb
  ),
  (
    'user_calvinharris',
    'artist',
    'calvinharris',
    'Calvin Harris',
    'Scottish DJ, record producer, and songwriter. One of the highest-paid DJs in the world. Known for hits like "Feel So Close" and "Summer."',
    'https://i.scdn.co/image/ab6761610000e5eb6e1b1bee0e4ea8c2b9e86d53',
    'https://open.spotify.com/artist/7CajNmpbOovFoOoasH2HaY',
    'https://music.apple.com/us/artist/calvin-harris/40265304',
    'https://youtube.com/@calvinharris',
    '7CajNmpbOovFoOoasH2HaY',
    true,
    true,
    '{"hide_branding": false}'::jsonb
  ),
  (
    'user_sabrinacarpenter',
    'artist',
    'sabrinacarpenter',
    'Sabrina Carpenter',
    'Singer-songwriter and actress known for her powerful vocals and relatable lyrics. Albums "Emails I Can''t Send" and "Short n'' Sweet" showcase her artistic growth.',
    'https://i.scdn.co/image/ab6761610000e5ebb5ccecf96c0cd5e423f6acaf',
    'https://open.spotify.com/artist/74KM79TiuVKeVCqs8QtB0B',
    'https://music.apple.com/us/artist/sabrina-carpenter/1141195867',
    'https://youtube.com/@sabrinacarpenter',
    '74KM79TiuVKeVCqs8QtB0B',
    true,
    true,
    '{"hide_branding": false}'::jsonb
  ),
  (
    'user_thechainsmokers',
    'artist',
    'thechainsmokers',
    'The Chainsmokers',
    'Electronic DJ duo known for hits like "Closer," "Don''t Let Me Down," and "Something Just Like This." Grammy-nominated producers Alex Pall and Drew Taggart.',
    'https://i.scdn.co/image/ab6761610000e5eb04710bb6ccb46e81b96f9fd3',
    'https://open.spotify.com/artist/69GGBxA162lTqCwzJG5jLp',
    'https://music.apple.com/us/artist/the-chainsmokers/1001089062',
    'https://youtube.com/@thechainsmokers',
    '69GGBxA162lTqCwzJG5jLp',
    true,
    true,
    '{"hide_branding": false}'::jsonb
  ),
  (
    'user_dualipa',
    'artist',
    'dualipa',
    'Dua Lipa',
    'British-Albanian singer known for dance-pop hits and retro-futuristic sound. Albums "Future Nostalgia" and "Radical Optimism" defined modern pop music.',
    'https://i.scdn.co/image/ab6761610000e5eb9a0bb7bdffa7893f1d25c326',
    'https://open.spotify.com/artist/6M2wZ9GZgrQXHCFfjv46we',
    'https://music.apple.com/us/artist/dua-lipa/1109397171',
    'https://youtube.com/@dualipa',
    '6M2wZ9GZgrQXHCFfjv46we',
    true,
    true,
    '{"hide_branding": false}'::jsonb
  ),
  (
    'user_31WSX2aM04NNT8bFAQppljnGuGN',
    'artist',
    'tim',
    'Tim White',
    'Music producer and software engineer. Known for ambient electronic compositions and innovative music technology. "Never Say A Word" available on all platforms.',
    'https://i.scdn.co/image/ab6761610000e5ebbab7ca6e76db7da72b58aa5c',
    'https://open.spotify.com/artist/4Uwpa6zW3zzCSQvooQNksm',
    'https://music.apple.com/us/artist/tim-white/1664648289',
    'https://youtube.com/@itstimwhite',
    '4Uwpa6zW3zzCSQvooQNksm',
    true,
    true,
    '{"hide_branding": false}'::jsonb
  )
ON CONFLICT (username) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  bio = EXCLUDED.bio,
  avatar_url = EXCLUDED.avatar_url,
  spotify_url = EXCLUDED.spotify_url,
  apple_music_url = EXCLUDED.apple_music_url,
  youtube_url = EXCLUDED.youtube_url,
  spotify_id = EXCLUDED.spotify_id,
  is_verified = EXCLUDED.is_verified,
  updated_at = now();