import type { Artist, CreatorProfile } from '@/types/db';

export const mockArtist: Artist = {
  id: 'artist-1',
  owner_user_id: 'user-1',
  handle: 'test-artist',
  spotify_id: 'spotify-id-1',
  name: 'Test Artist',
  image_url: 'https://example.com/image.jpg',
  tagline: 'Test artist tagline',
  theme: {},
  settings: { hide_branding: false },
  spotify_url: 'https://open.spotify.com/artist/123',
  apple_music_url: 'https://music.apple.com/artist/123',
  youtube_url: 'https://youtube.com/channel/123',
  published: true,
  is_verified: false,
  is_featured: false,
  marketing_opt_out: false,
  created_at: '2023-01-01T00:00:00.000Z',
};

export const mockCreatorProfile: CreatorProfile = {
  id: 'profile-1',
  user_id: 'user-1',
  creator_type: 'artist',
  username: 'test-artist',
  display_name: 'Test Artist',
  bio: 'Test artist bio',
  avatar_url: 'https://example.com/image.jpg',
  spotify_url: 'https://open.spotify.com/artist/123',
  apple_music_url: 'https://music.apple.com/artist/123',
  youtube_url: 'https://youtube.com/channel/123',
  spotify_id: 'spotify-id-1',
  is_public: true,
  is_verified: false,
  is_featured: false,
  marketing_opt_out: false,
  is_claimed: true,
  claim_token: null,
  claimed_at: '2023-01-01T00:00:00.000Z',
  profile_views: 0,
  username_normalized: 'test-artist',
  search_text: 'test artist',
  display_title: 'Test Artist',
  profile_completion_pct: 80,
  settings: {},
  theme: {},
  created_at: '2023-01-01T00:00:00.000Z',
  updated_at: '2023-01-01T00:00:00.000Z',
};

