name: Branch Protections (Manual Management)

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  note:
    name: No-op placeholder
    runs-on: ubuntu-latest
    steps:
      - name: Branch protections managed manually
        run: |
          echo "Branch protections are managed manually in repository settings."
          echo "This workflow is intentionally a no-op placeholder."
