name: CI

on:
  pull_request:
    branches: [preview, main]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '.vscode/**'
  push:
    branches: [preview, main]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-policy:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const base = context.payload.pull_request.base.ref;
            const head = context.payload.pull_request.head.ref;
            if (base === 'main' && head !== 'preview') {
              core.setFailed(`Only allow preview -> main. Got ${head} -> ${base}`);
            } else if (base === 'preview' && head === 'main') {
              core.setFailed(`Do not merge main -> preview. Use feature/* -> preview`);
            } else {
              core.info('PR policy OK');
            }

  up-to-date-with-preview:
    name: up-to-date-with-preview
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'preview' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Check branch is up-to-date with preview
        run: |
          git fetch origin preview
          if git merge-base --is-ancestor origin/preview HEAD; then
            echo "Up to date with preview"
          else
            echo "Branch is behind preview. Please merge/rebase preview into your branch."
            exit 1
          fi

  ci-typecheck:
    # Draft PRs skip; ready PRs + pushes run fast checks in parallel
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'true'
      - uses: actions/checkout@v4
        with: { fetch-depth: 2 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Install
        run: npm ci
      - name: Typecheck
        run: npm run typecheck --if-present

  ci-lint:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'true'
      - uses: actions/checkout@v4
        with: { fetch-depth: 2 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint --if-present

  ci-full:
    name: Full CI (label or push)
    needs: [ci-typecheck, ci-lint]
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'full-ci')) }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 2
          
      # Path guard: Check if changes affect critical files
      - name: Check for relevant changes
        id: check_changes
        run: |
          # Force run if full-ci label is present
          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'full-ci') }}" == "true" ]]; then
            echo "Forcing full CI run due to 'full-ci' label"
            echo "run_full_ci=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # For push events to main/preview, always run full CI
          if [[ "${{ github.event_name }}" == "push" && ("${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == "refs/heads/preview") ]]; then
            echo "Running full CI for push to main/preview branch"
            echo "run_full_ci=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Get changed files
          git fetch origin ${{ github.base_ref || 'HEAD~1' }}
          CHANGED_FILES=$(git diff --name-only FETCH_HEAD HEAD)
          
          # Check if critical paths were modified
          echo "Checking for changes in critical paths..."
          if echo "$CHANGED_FILES" | grep -q -E '^(app/|components/|lib/|tests/|package.*\.json|next\.config\.js)'; then
            echo "Critical paths changed, running full CI"
            echo "run_full_ci=true" >> $GITHUB_OUTPUT
          else
            echo "No critical paths changed, skipping full CI"
            echo "run_full_ci=false" >> $GITHUB_OUTPUT
            echo "Changed files:"
            echo "$CHANGED_FILES"
          fi
      
      # Skip remaining steps if no relevant changes
      - name: Skip notification
        if: steps.check_changes.outputs.run_full_ci != 'true'
        run: |
          echo "Skipping full CI as no critical paths were changed."
          echo "To force a full CI run, add the 'full-ci' label to the PR."
          exit 0
          
      # Continue with CI steps only if relevant changes detected or full-ci label present
      - uses: actions/setup-node@v4
        if: steps.check_changes.outputs.run_full_ci == 'true'
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: '**/package-lock.json'
          
      - name: Install dependencies
        if: steps.check_changes.outputs.run_full_ci == 'true'
        run: npm ci
        
      - name: Cache Playwright browsers
        if: ${{ steps.check_changes.outputs.run_full_ci == 'true' && (hashFiles('tests/e2e/**') != '' || hashFiles('tests/smoke/**') != '') }}
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
          
      - name: Install Playwright
        if: ${{ steps.check_changes.outputs.run_full_ci == 'true' && (hashFiles('tests/e2e/**') != '' || hashFiles('tests/smoke/**') != '') }}
        run: npx playwright install --with-deps
        
      - name: E2E smoke
        if: ${{ steps.check_changes.outputs.run_full_ci == 'true' && github.ref != 'refs/heads/main' && (hashFiles('tests/e2e/**') != '' || hashFiles('tests/smoke/**') != '') }}
        run: npm run e2e:smoke --if-present
        continue-on-error: true
        
      - name: Run tests
        if: steps.check_changes.outputs.run_full_ci == 'true'
        run: npm test --if-present
        
      - name: Build
        if: steps.check_changes.outputs.run_full_ci == 'true'
        run: npm run build --if-present

  deploy:
    needs: [ci-typecheck, ci-lint] # change to [ci-full] if you want build/tests first
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/preview' }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: Preview
      url: https://preview.jov.ie
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install Vercel CLI
        run: npm i -g vercel@latest
      - name: DB migrate (preview)
        run: npm run db:migrate
        env:
          GIT_BRANCH: preview
        continue-on-error: true
      - name: DB seed (preview)
        run: npm run db:seed
        env:
          GIT_BRANCH: preview
        continue-on-error: true
      - name: Pull env (preview)
        run: vercel pull --yes --environment=preview --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - name: Build
        run: vercel build --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - name: Deploy (prebuilt)
        run: vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  promote:
    needs: [deploy]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/preview' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 2 }
      - name: Create/Update PR preview → main (manual review required)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if PR already exists
          existing_pr=$(gh pr list --head preview --base main --json number --jq '.[0].number // empty')
          if [ -z "$existing_pr" ]; then
            echo "Creating new PR: preview → main"
            gh pr create --base main --head preview --title "Promote: preview → main" --body "Automated promotion PR (manual review required)"
          else
            echo "PR already exists: #$existing_pr (no auto-merge; manual review required)"
            gh pr edit "$existing_pr" --title "Promote: preview → main" --body "Automated promotion PR (manual review required)"
          fi

  deploy-prod:
    needs: [ci-typecheck, ci-lint]
    if: ${{ github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment:
      name: Production
      url: https://jov.ie
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Vercel CLI
        run: npm i -g vercel@latest
      - name: DB migrate (main) — requires backup and ALLOW_PROD_MIGRATIONS=true
        run: npm run db:migrate
        env:
          GIT_BRANCH: main
        continue-on-error: false
      - name: Pull env (production)
        run: vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - name: Build (production)
        run: vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - name: Deploy (production, prebuilt)
        run: vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
