name: Plan → Issues → Copilot

on:
  push:
    paths:
      - 'windsurf.plan.md'
      - 'plan.md'
      - 'PLAN.md'
      - '.github/scripts/plan2issues.mjs'
      - '.github/scripts/plan2issues.v2.mjs'
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: {}

# No top-level env defaults to avoid actionlint warnings; script provides fallbacks

jobs:
  sync:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    concurrency:
      group: plan-sync
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Octokit (runtime)
        run: npm i octokit@latest --no-save --silent
      - name: Sync plan to issues and assign Copilot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          COPILOT_ASSIGNEE: github-copilot
        run: node .github/scripts/plan2issues.v2.mjs
