name: Promote Dev → Preview (Manual)

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peter-evans/create-pull-request@v6
        with:
          title: 'Promote dev → preview'
          body: 'Manual promotion trigger.'
          branch: promote/dev-to-preview
          base: preview
          delete-branch: true
          labels: ci, promotion
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.create_pull_request.outputs.pull-request-number }}
          merge-method: squash
