name: Refresh Spotify Artists

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger edge function
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          set -e
          STATUS=$(curl -s -o response.json -w "%{http_code}" "$SUPABASE_URL/functions/v1/refresh-spotify-artists" \
            -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
            -H "Content-Type: application/json")
          cat response.json
          if [ "$STATUS" -ge 400 ]; then
            exit 1
          fi
