name: Dev Rapid Loop

on:
  push:
    branches: [dev]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  rapid:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.DEV_NEXT_PUBLIC_SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.DEV_SUPABASE_SERVICE_ROLE_KEY }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.DEV_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.DEV_CLERK_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - run: npm run typecheck --if-present
      - run: npm run lint --if-present
      - run: npm run test --if-present -- --ci
      - run: npm run build

      - name: Vercel pull preview env
        run: npx vercel pull --environment=preview --yes --token "$VERCEL_TOKEN"

      - name: Vercel build
        run: npx vercel build --token "$VERCEL_TOKEN"

      - name: Vercel deploy (preview)
        id: vercel
        run: |
          URL=$(npx vercel deploy --prebuilt --token "$VERCEL_TOKEN")
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Playwright E2E (smoke)
        run: |
          npx playwright install --with-deps
          BASE_URL="${{ steps.vercel.outputs.url }}" npm run e2e:smoke --if-present

      - name: Lighthouse budgets
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: ${{ steps.vercel.outputs.url }}
          configPath: .lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Dependency security (high+)
        run: npx audit-ci --moderate --allowlist "npm:*" || npm audit --audit-level=high

  promote:
    needs: rapid
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create/Update PR dev → preview
        uses: peter-evans/create-pull-request@v6
        with:
          title: 'Promote dev → preview'
          body: 'Automated promotion from dev.'
          branch: promote/dev-to-preview
          base: preview
          delete-branch: true
          labels: ci, promotion

      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.create_pull_request.outputs.pull-request-number }}
          merge-method: squash
