name: Lighthouse CI

on:
  pull_request:
    branches: [ dev ]
    types: [opened, synchronize, reopened]
  push:
    branches: [ dev ]

permissions:
  contents: read

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - run: npm run build

      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: http://localhost:3000
          configPath: .lighthouserc.json
          startServerCommand: npm start
          uploadArtifacts: true
          temporaryPublicStorage: true
