name: Preview Confidence Loop

on:
  push:
    branches: [preview]
  schedule:
    - cron: '0 8 * * *' # daily 08:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: write

jobs:
  confidence:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.PREVIEW_NEXT_PUBLIC_SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.PREVIEW_SUPABASE_SERVICE_ROLE_KEY }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.PREVIEW_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.PREVIEW_CLERK_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.17
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - name: Vercel pull preview env
        run: npx vercel pull --environment=preview --yes --token "$VERCEL_TOKEN"

      - name: Vercel build
        run: npx vercel build --token "$VERCEL_TOKEN"

      - name: Vercel deploy (preview)
        id: vercel
        run: |
          URL=$(npx vercel deploy --prebuilt --token "$VERCEL_TOKEN")
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Playwright E2E (full, desktop+mobile)
        run: |
          npx playwright install --with-deps
          BASE_URL="${{ steps.vercel.outputs.url }}" npm run e2e:full --if-present

      - name: Visual regression
        run: |
          BASE_URL="${{ steps.vercel.outputs.url }}" npm run vr:ci --if-present

      - name: Lighthouse (budgeted)
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            ${{ steps.vercel.outputs.url }}
            ${{ steps.vercel.outputs.url }}/auth/sign-in
            ${{ steps.vercel.outputs.url }}/links/demo
          configPath: .lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Bundle size (size-limit)
        run: npx size-limit || (echo "Bundle size exceeded" && exit 1)

      - name: ZAP Baseline DAST
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: ${{ steps.vercel.outputs.url }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Dependency security (high+)
        run: npx audit-ci --moderate --allowlist "npm:*" || npm audit --audit-level=high
