name: 'Branch Protection Rules'
description: 'Enforces branch protection rules for main, preview, and develop branches'
target:
  branch:
    - 'main'
    - 'preview'
    - 'develop'
rules:
  - name: 'Require status checks to pass before merging'
    enforcement: 'active'
    parameters:
      required_status_checks:
        strict: true
        contexts:
          # Core CI checks
          - 'build'
          - 'test'
          - 'lint'
          - 'typecheck'
          - 'security-audit'
          # PR verification
          - 'verify-pr-source'
          - 'verify-required-checks'
          - 'verify-workflow-requirements'
          # Security and quality
          - 'codeql'
          # E2E tests (when enabled)
          - 'e2e:smoke'
          - 'e2e:full'
          - 'a11y:ci'
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews_on_push: true
        require_code_owner_reviews: false
        require_last_push_approval: true
      required_workflows:
        - 'web-pr-verify.yml'
        - 'codeql.yml'
        - 'develop-ci.yml'
        - 'preview-ci.yml'
      required_deployments:
        required_environments:
          - 'production'
          - 'preview'
      required_conversation_resolution: true
      required_linear_history: false
      allow_force_pushes: false
      allow_deletions: false
      block_creations: false
      required_signatures: false
