name: 'Branch Protection Rules'
description: 'Enforces branch protection rules for main, preview, and develop branches'
target:
  branch:
    - 'main'
    - 'preview'
    - 'develop'
rules:
  - name: 'Require status checks to pass before merging'
    enforcement: 'active'
    parameters:
      required_status_checks:
        strict: true
        contexts:
          # Core CI checks (from web-pr-verify.yml)
          - 'build'
          - 'test'
          - 'lint'
          - 'typecheck'
          # PR verification (from web-pr-verify.yml)
          - 'verify-pr-source'
          # Security (from codeql.yml - matrix jobs)
          - 'Analyze (actions)'
          - 'Analyze (javascript-typescript)'
      required_pull_request_reviews:
        required_approving_review_count: 0
        dismiss_stale_reviews_on_push: true
        require_code_owner_reviews: false
        require_last_push_approval: false
      required_workflows:
        - 'web-pr-verify.yml'
        - 'codeql.yml'
      required_conversation_resolution: true
      required_linear_history: false
      allow_force_pushes: false
      allow_deletions: false
      block_creations: false
      required_signatures: false
