name: 'Code Quality Rules'
description: 'Enforces code quality standards including linting, testing, and formatting'
target:
  repository:
    - 'itstimwhite/Jovie'
rules:
  - name: 'Require code quality checks to pass'
    enforcement: 'active'
    parameters:
      required_status_checks:
        strict: true
        contexts:
          - 'lint'
          - 'typecheck'
          - 'test'
          - 'format'
          - 'build'
  - name: 'Require test coverage to meet minimum threshold'
    enforcement: 'active'
    parameters:
      required_status_checks:
        strict: true
        contexts:
          - 'test-coverage'
  - name: 'Require all tests to pass'
    enforcement: 'active'
    parameters:
      required_status_checks:
        strict: true
        contexts:
          - 'unit-tests'
          - 'integration-tests'
          - 'e2e-tests'
  - name: 'Require accessibility tests to pass'
    enforcement: 'active'
    parameters:
      required_status_checks:
        strict: true
        contexts:
          - 'a11y:ci'
  - name: 'Require performance tests to pass'
    enforcement: 'active'
    parameters:
      required_status_checks:
        strict: true
        contexts:
          - 'lighthouse'
          - 'performance'
  - name: 'Require code formatting to be consistent'
    enforcement: 'active'
    parameters:
      required_status_checks:
        strict: true
        contexts:
          - 'prettier'
          - 'eslint'
  - name: 'Require TypeScript compilation to succeed'
    enforcement: 'active'
    parameters:
      required_status_checks:
        strict: true
        contexts:
          - 'typecheck'
