# EXAMPLE ONLY - NOT APPLIED
# This ruleset references many contexts we don't emit yet and would block merges
# Move to docs/ruleset-examples/ or uncomment when we implement these checks
name: 'Security Rules'
description: 'Security-focused rules for vulnerability scanning and code security'
target:
  repository:
    - 'itstimwhite/Jovie'
rules:
  - name: 'Require security analysis to pass before merging'
    enforcement: 'active'
    parameters:
      required_status_checks:
        strict: true
        contexts:
          - 'CodeQL'
          - 'Dependency Review'
          - 'Secret scanning'
          - 'Dependabot'
  - name: 'Require dependency review before merging'
    enforcement: 'active'
  - name: 'Require secret scanning before merging'
    enforcement: 'active'
  - name: 'Require code scanning before merging'
    enforcement: 'active'
  - name: 'Require vulnerability alerts to be resolved'
    enforcement: 'active'
  - name: 'Require security policy to be present'
    enforcement: 'active'
  - name: 'Require security advisories to be reviewed'
    enforcement: 'active'
  - name: 'Require security updates to be applied'
    enforcement: 'active'
  - name: 'Require security testing to pass'
    enforcement: 'active'
    parameters:
      required_status_checks:
        strict: true
        contexts:
          - 'security-scan'
          - 'vulnerability-scan'
          - 'dependency-check'
